version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - ..:/workspace:cached
    ports:
      - 8000:8000
    command: sleep infinity

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017